-- Clean existing
DELETE FROM score_messages;
DELETE FROM scores;
DELETE FROM satisfaction_surveys;
DELETE FROM enrollments;
DELETE FROM course_objectives;
DELETE FROM courses;
DELETE FROM users;

-- Users
INSERT INTO users (id, username, password, role, name) VALUES (1, 'sec1', '123456', 'SECRETARY', 'Secretary One');
INSERT INTO users (id, username, password, role, name) VALUES (2, 'sec2', '123456', 'SECRETARY', 'Secretary Two');
INSERT INTO users (id, username, password, role, name) VALUES (3, 'tea1', '123456', 'TEACHER', 'Teacher Primary');
INSERT INTO users (id, username, password, role, name) VALUES (4, 'tea2', '123456', 'TEACHER', 'Teacher Secondary');
INSERT INTO users (id, username, password, role, name) VALUES (5, 'stu001', '123456', 'STUDENT', 'Student 1');
INSERT INTO users (id, username, password, role, name) VALUES (6, 'stu002', '123456', 'STUDENT', 'Student 2');
INSERT INTO users (id, username, password, role, name) VALUES (7, 'stu003', '123456', 'STUDENT', 'Student 3');
INSERT INTO users (id, username, password, role, name) VALUES (8, 'stu004', '123456', 'STUDENT', 'Student 4');
INSERT INTO users (id, username, password, role, name) VALUES (9, 'stu005', '123456', 'STUDENT', 'Student 5');
INSERT INTO users (id, username, password, role, name) VALUES (10, 'stu006', '123456', 'STUDENT', 'Student 6');
INSERT INTO users (id, username, password, role, name) VALUES (11, 'stu007', '123456', 'STUDENT', 'Student 7');
INSERT INTO users (id, username, password, role, name) VALUES (12, 'stu008', '123456', 'STUDENT', 'Student 8');
INSERT INTO users (id, username, password, role, name) VALUES (13, 'stu009', '123456', 'STUDENT', 'Student 9');
INSERT INTO users (id, username, password, role, name) VALUES (14, 'stu010', '123456', 'STUDENT', 'Student 10');
INSERT INTO users (id, username, password, role, name) VALUES (15, 'stu011', '123456', 'STUDENT', 'Student 11');
INSERT INTO users (id, username, password, role, name) VALUES (16, 'stu012', '123456', 'STUDENT', 'Student 12');
INSERT INTO users (id, username, password, role, name) VALUES (17, 'stu013', '123456', 'STUDENT', 'Student 13');
INSERT INTO users (id, username, password, role, name) VALUES (18, 'stu014', '123456', 'STUDENT', 'Student 14');
INSERT INTO users (id, username, password, role, name) VALUES (19, 'stu015', '123456', 'STUDENT', 'Student 15');
INSERT INTO users (id, username, password, role, name) VALUES (20, 'stu016', '123456', 'STUDENT', 'Student 16');
INSERT INTO users (id, username, password, role, name) VALUES (21, 'stu017', '123456', 'STUDENT', 'Student 17');
INSERT INTO users (id, username, password, role, name) VALUES (22, 'stu018', '123456', 'STUDENT', 'Student 18');
INSERT INTO users (id, username, password, role, name) VALUES (23, 'stu019', '123456', 'STUDENT', 'Student 19');
INSERT INTO users (id, username, password, role, name) VALUES (24, 'stu020', '123456', 'STUDENT', 'Student 20');
INSERT INTO users (id, username, password, role, name) VALUES (25, 'stu021', '123456', 'STUDENT', 'Student 21');
INSERT INTO users (id, username, password, role, name) VALUES (26, 'stu022', '123456', 'STUDENT', 'Student 22');
INSERT INTO users (id, username, password, role, name) VALUES (27, 'stu023', '123456', 'STUDENT', 'Student 23');
INSERT INTO users (id, username, password, role, name) VALUES (28, 'stu024', '123456', 'STUDENT', 'Student 24');
INSERT INTO users (id, username, password, role, name) VALUES (29, 'stu025', '123456', 'STUDENT', 'Student 25');
INSERT INTO users (id, username, password, role, name) VALUES (30, 'stu026', '123456', 'STUDENT', 'Student 26');
INSERT INTO users (id, username, password, role, name) VALUES (31, 'stu027', '123456', 'STUDENT', 'Student 27');
INSERT INTO users (id, username, password, role, name) VALUES (32, 'stu028', '123456', 'STUDENT', 'Student 28');
INSERT INTO users (id, username, password, role, name) VALUES (33, 'stu029', '123456', 'STUDENT', 'Student 29');
INSERT INTO users (id, username, password, role, name) VALUES (34, 'stu030', '123456', 'STUDENT', 'Student 30');
INSERT INTO users (id, username, password, role, name) VALUES (35, 'stu031', '123456', 'STUDENT', 'Student 31');
INSERT INTO users (id, username, password, role, name) VALUES (36, 'stu032', '123456', 'STUDENT', 'Student 32');
INSERT INTO users (id, username, password, role, name) VALUES (37, 'stu033', '123456', 'STUDENT', 'Student 33');
INSERT INTO users (id, username, password, role, name) VALUES (38, 'stu034', '123456', 'STUDENT', 'Student 34');
INSERT INTO users (id, username, password, role, name) VALUES (39, 'stu035', '123456', 'STUDENT', 'Student 35');
INSERT INTO users (id, username, password, role, name) VALUES (40, 'stu036', '123456', 'STUDENT', 'Student 36');
INSERT INTO users (id, username, password, role, name) VALUES (41, 'stu037', '123456', 'STUDENT', 'Student 37');
INSERT INTO users (id, username, password, role, name) VALUES (42, 'stu038', '123456', 'STUDENT', 'Student 38');
INSERT INTO users (id, username, password, role, name) VALUES (43, 'stu039', '123456', 'STUDENT', 'Student 39');
INSERT INTO users (id, username, password, role, name) VALUES (44, 'stu040', '123456', 'STUDENT', 'Student 40');
INSERT INTO users (id, username, password, role, name) VALUES (45, 'stu041', '123456', 'STUDENT', 'Student 41');
INSERT INTO users (id, username, password, role, name) VALUES (46, 'stu042', '123456', 'STUDENT', 'Student 42');
INSERT INTO users (id, username, password, role, name) VALUES (47, 'stu043', '123456', 'STUDENT', 'Student 43');
INSERT INTO users (id, username, password, role, name) VALUES (48, 'stu044', '123456', 'STUDENT', 'Student 44');
INSERT INTO users (id, username, password, role, name) VALUES (49, 'stu045', '123456', 'STUDENT', 'Student 45');
INSERT INTO users (id, username, password, role, name) VALUES (50, 'stu046', '123456', 'STUDENT', 'Student 46');
INSERT INTO users (id, username, password, role, name) VALUES (51, 'stu047', '123456', 'STUDENT', 'Student 47');
INSERT INTO users (id, username, password, role, name) VALUES (52, 'stu048', '123456', 'STUDENT', 'Student 48');
INSERT INTO users (id, username, password, role, name) VALUES (53, 'stu049', '123456', 'STUDENT', 'Student 49');
INSERT INTO users (id, username, password, role, name) VALUES (54, 'stu050', '123456', 'STUDENT', 'Student 50');
INSERT INTO users (id, username, password, role, name) VALUES (55, 'stu051', '123456', 'STUDENT', 'Student 51');
INSERT INTO users (id, username, password, role, name) VALUES (56, 'stu052', '123456', 'STUDENT', 'Student 52');
INSERT INTO users (id, username, password, role, name) VALUES (57, 'stu053', '123456', 'STUDENT', 'Student 53');
INSERT INTO users (id, username, password, role, name) VALUES (58, 'stu054', '123456', 'STUDENT', 'Student 54');
INSERT INTO users (id, username, password, role, name) VALUES (59, 'stu055', '123456', 'STUDENT', 'Student 55');
INSERT INTO users (id, username, password, role, name) VALUES (60, 'stu056', '123456', 'STUDENT', 'Student 56');
INSERT INTO users (id, username, password, role, name) VALUES (61, 'stu057', '123456', 'STUDENT', 'Student 57');
INSERT INTO users (id, username, password, role, name) VALUES (62, 'stu058', '123456', 'STUDENT', 'Student 58');
INSERT INTO users (id, username, password, role, name) VALUES (63, 'stu059', '123456', 'STUDENT', 'Student 59');
INSERT INTO users (id, username, password, role, name) VALUES (64, 'stu060', '123456', 'STUDENT', 'Student 60');
INSERT INTO users (id, username, password, role, name) VALUES (65, 'stu061', '123456', 'STUDENT', 'Student 61');
INSERT INTO users (id, username, password, role, name) VALUES (66, 'stu062', '123456', 'STUDENT', 'Student 62');
INSERT INTO users (id, username, password, role, name) VALUES (67, 'stu063', '123456', 'STUDENT', 'Student 63');
INSERT INTO users (id, username, password, role, name) VALUES (68, 'stu064', '123456', 'STUDENT', 'Student 64');
INSERT INTO users (id, username, password, role, name) VALUES (69, 'stu065', '123456', 'STUDENT', 'Student 65');
INSERT INTO users (id, username, password, role, name) VALUES (70, 'stu066', '123456', 'STUDENT', 'Student 66');
INSERT INTO users (id, username, password, role, name) VALUES (71, 'stu067', '123456', 'STUDENT', 'Student 67');
INSERT INTO users (id, username, password, role, name) VALUES (72, 'stu068', '123456', 'STUDENT', 'Student 68');
INSERT INTO users (id, username, password, role, name) VALUES (73, 'stu069', '123456', 'STUDENT', 'Student 69');
INSERT INTO users (id, username, password, role, name) VALUES (74, 'stu070', '123456', 'STUDENT', 'Student 70');
INSERT INTO users (id, username, password, role, name) VALUES (75, 'stu071', '123456', 'STUDENT', 'Student 71');
INSERT INTO users (id, username, password, role, name) VALUES (76, 'stu072', '123456', 'STUDENT', 'Student 72');
INSERT INTO users (id, username, password, role, name) VALUES (77, 'stu073', '123456', 'STUDENT', 'Student 73');
INSERT INTO users (id, username, password, role, name) VALUES (78, 'stu074', '123456', 'STUDENT', 'Student 74');
INSERT INTO users (id, username, password, role, name) VALUES (79, 'stu075', '123456', 'STUDENT', 'Student 75');
INSERT INTO users (id, username, password, role, name) VALUES (80, 'stu076', '123456', 'STUDENT', 'Student 76');
INSERT INTO users (id, username, password, role, name) VALUES (81, 'stu077', '123456', 'STUDENT', 'Student 77');
INSERT INTO users (id, username, password, role, name) VALUES (82, 'stu078', '123456', 'STUDENT', 'Student 78');
INSERT INTO users (id, username, password, role, name) VALUES (83, 'stu079', '123456', 'STUDENT', 'Student 79');
INSERT INTO users (id, username, password, role, name) VALUES (84, 'stu080', '123456', 'STUDENT', 'Student 80');

-- Course
INSERT INTO courses (id, course_code, course_name, semester, teacher_id, class_time, location) VALUES (1, 'ENG101', 'Software Engineering', '2026-Spring', 3, '周一 第1-2节', '教一101');

-- Course Objectives
INSERT INTO course_objectives (course_id, objective_index, description, regular_weight, test_weight, lab_weight, final_weight) VALUES (1, 1, 'Objective 1: Theory', 0.4, 0.4, 0.2, 0.5);
INSERT INTO course_objectives (course_id, objective_index, description, regular_weight, test_weight, lab_weight, final_weight) VALUES (1, 2, 'Objective 2: Practice', 0.6, 0.6, 0.8, 0.5);
INSERT INTO enrollments (student_id, course_id) VALUES (5, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (6, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (7, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (8, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (9, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (10, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (11, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (12, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (13, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (14, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (15, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (16, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (17, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (18, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (19, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (20, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (21, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (22, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (23, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (24, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (25, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (26, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (27, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (28, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (29, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (30, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (31, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (32, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (33, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (34, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (35, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (36, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (37, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (38, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (39, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (40, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (41, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (42, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (43, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (44, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (45, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (46, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (47, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (48, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (49, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (50, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (51, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (52, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (53, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (54, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (55, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (56, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (57, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (58, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (59, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (60, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (61, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (62, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (63, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (64, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (65, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (66, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (67, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (68, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (69, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (70, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (71, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (72, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (73, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (74, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (75, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (76, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (77, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (78, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (79, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (80, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (81, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (82, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (83, 1);
INSERT INTO enrollments (student_id, course_id) VALUES (84, 1);

-- Scores
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, absence_count, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (5, 1, 93, 85, 86, 86, 81, 87, 85, 90, 91, 87, 3, 87.90, 84.75, 90.80, 87.87, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (5, 1, '非常满意');
INSERT INTO score_messages (course_id, student_id, teacher_id, question_text, question_attachment, reply_text, reply_attachment, status) VALUES (1, 5, 3, '老师您好，我想确认一下实验报告的扣分点，感觉自己这部分理解得还不够清楚。', NULL, '实验报告主要扣在结果分析不够展开，你可以对照评分标准补看第3章示例。', NULL, 'REPLIED');
INSERT INTO score_messages (course_id, student_id, teacher_id, question_text, question_attachment, reply_text, reply_attachment, status) VALUES (1, 6, 3, '老师，我最近几次测验波动比较大，有点担心后面会不会继续掉分，想问下应该优先补哪部分。', NULL, NULL, NULL, 'PENDING');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (6, 1, 93, 92, 95, 88, 96, 98, 91, 94, 88, 93, 93.80, 93.25, 89.20, 92.07, '优秀');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (7, 1, 100, 95, 93, 95, 95, 88, 88, 93, 92, 95, 95.50, 91.50, 92.20, 93.56, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (7, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (8, 1, 77, 69, 63, 71, 63, 72, 68, 74, 63, 70, 68.40, 68.50, 65.20, 67.94, '及格');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (9, 1, 85, 80, 78, 70, 75, 78, 75, 84, 72, 77, 80.50, 74.50, 74.40, 76.42, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (9, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (10, 1, 92, 85, 78, 82, 80, 83, 86, 89, 79, 85, 83.60, 82.75, 81.00, 83.07, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (10, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (11, 1, 35, 28, 32, 34, 33, 32, 37, 42, 32, 36, 32.10, 34.00, 34.00, 34.22, '不及格');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (12, 1, 78, 75, 78, 73, 72, 71, 73, 75, 72, 73, 77.40, 72.25, 72.60, 73.61, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (12, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (13, 1, 77, 76, 74, 78, 71, 75, 69, 81, 77, 71, 75.30, 73.25, 77.80, 74.35, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (13, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (14, 1, 94, 94, 86, 95, 88, 86, 89, 92, 92, 88, 90.00, 89.50, 92.00, 89.90, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (14, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (15, 1, 100, 99, 98, 95, 97, 98, 100, 100, 94, 94, 98.80, 97.50, 95.20, 96.02, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (15, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (16, 1, 97, 84, 87, 87, 86, 94, 84, 94, 88, 94, 89.40, 87.75, 89.20, 90.39, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (16, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (17, 1, 92, 86, 90, 89, 96, 95, 92, 95, 87, 89, 89.80, 93.00, 88.60, 89.84, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (18, 1, 79, 81, 81, 74, 78, 76, 74, 85, 80, 74, 80.40, 75.50, 81.00, 77.68, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (18, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (19, 1, 98, 96, 86, 96, 87, 96, 86, 99, 93, 96, 91.60, 91.25, 94.20, 93.63, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (19, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (20, 1, 78, 74, 74, 73, 74, 80, 76, 84, 82, 82, 75.20, 75.75, 82.40, 79.51, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (21, 1, 76, 74, 78, 75, 75, 73, 77, 77, 77, 78, 76.60, 75.00, 77.00, 76.82, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (21, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (22, 1, 83, 75, 72, 71, 78, 71, 76, 83, 71, 72, 75.90, 74.00, 73.40, 73.60, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (23, 1, 87, 75, 73, 76, 82, 75, 77, 87, 73, 73, 77.60, 77.50, 75.80, 75.66, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (23, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (24, 1, 77, 80, 76, 76, 74, 72, 75, 85, 78, 79, 77.10, 74.25, 79.40, 77.79, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (24, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (25, 1, 100, 92, 95, 96, 97, 100, 100, 97, 100, 96, 95.90, 98.25, 99.40, 97.45, '优秀');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (26, 1, 70, 66, 68, 68, 61, 62, 63, 73, 69, 66, 68.20, 63.50, 69.80, 67.08, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (26, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (27, 1, 100, 98, 92, 100, 100, 94, 98, 100, 99, 97, 95.60, 98.00, 99.20, 97.58, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (27, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (28, 1, 100, 100, 96, 96, 94, 100, 100, 100, 100, 96, 98.00, 97.50, 100.00, 97.90, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (28, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (29, 1, 80, 75, 76, 80, 78, 77, 78, 83, 79, 77, 77.00, 78.25, 79.80, 78.09, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (30, 1, 100, 94, 92, 94, 96, 98, 91, 94, 97, 91, 94.80, 94.75, 96.40, 94.13, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (30, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (31, 1, 75, 73, 68, 68, 69, 76, 78, 81, 68, 68, 71.10, 72.75, 70.60, 70.35, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (31, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (32, 1, 100, 92, 95, 98, 100, 95, 93, 100, 100, 92, 95.90, 96.50, 100.00, 96.08, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (32, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (33, 1, 51, 52, 43, 49, 52, 52, 44, 54, 46, 51, 47.20, 49.25, 47.60, 48.87, '不及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (33, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (34, 1, 94, 90, 97, 89, 93, 92, 91, 92, 96, 91, 94.70, 91.25, 95.20, 93.05, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (34, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (35, 1, 75, 75, 77, 70, 74, 73, 76, 76, 79, 72, 76.00, 73.25, 78.40, 74.97, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (35, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (36, 1, 100, 94, 97, 93, 97, 99, 100, 97, 97, 92, 97.30, 97.25, 97.00, 95.61, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (36, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (37, 1, 65, 65, 59, 65, 61, 65, 57, 71, 64, 64, 62.00, 62.00, 65.40, 63.62, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (37, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (38, 1, 90, 89, 87, 85, 92, 89, 87, 99, 86, 85, 88.30, 88.25, 88.60, 87.39, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (38, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (39, 1, 75, 68, 72, 66, 75, 73, 69, 80, 65, 66, 72.10, 70.75, 68.00, 68.77, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (39, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (40, 1, 77, 66, 67, 74, 71, 69, 67, 80, 76, 66, 69.80, 70.25, 76.80, 70.85, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (40, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (41, 1, 86, 75, 83, 77, 79, 79, 79, 79, 73, 76, 82.30, 78.50, 74.20, 77.22, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (42, 1, 90, 85, 84, 82, 83, 86, 83, 86, 81, 83, 86.00, 83.50, 82.00, 83.40, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (43, 1, 88, 78, 78, 83, 80, 79, 86, 90, 85, 86, 81.00, 82.00, 86.00, 84.20, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (43, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (44, 1, 65, 55, 64, 56, 55, 64, 59, 70, 59, 63, 62.50, 58.50, 61.20, 61.46, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (44, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (45, 1, 82, 83, 79, 84, 81, 79, 77, 86, 85, 82, 80.70, 80.25, 85.20, 82.35, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (46, 1, 80, 79, 81, 81, 73, 74, 71, 78, 73, 79, 80.30, 74.75, 74.00, 76.91, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (46, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (47, 1, 78, 67, 67, 72, 64, 63, 67, 70, 63, 69, 70.30, 66.50, 64.40, 67.38, '及格');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (48, 1, 86, 89, 90, 81, 91, 85, 83, 87, 87, 85, 88.60, 85.00, 87.00, 86.32, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (48, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (49, 1, 83, 77, 82, 75, 84, 82, 77, 84, 80, 75, 81.30, 79.50, 80.80, 78.90, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (50, 1, 81, 81, 83, 80, 76, 80, 79, 85, 83, 86, 82.00, 78.75, 83.40, 82.97, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (51, 1, 51, 47, 42, 50, 45, 50, 44, 50, 50, 43, 45.70, 47.25, 50.00, 46.49, '不及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (51, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (52, 1, 83, 78, 79, 78, 71, 79, 71, 79, 73, 75, 80.00, 74.75, 74.20, 75.71, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (53, 1, 89, 83, 88, 79, 85, 88, 83, 86, 85, 79, 87.30, 83.75, 85.20, 83.47, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (53, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (54, 1, 79, 76, 73, 79, 74, 72, 77, 83, 80, 79, 75.40, 75.50, 80.60, 78.06, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (54, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (55, 1, 68, 64, 63, 64, 64, 64, 62, 71, 63, 68, 64.70, 63.50, 64.60, 65.42, '及格');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (56, 1, 72, 72, 70, 75, 67, 67, 67, 82, 68, 70, 71.00, 69.00, 70.80, 70.24, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (56, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (57, 1, 100, 100, 94, 95, 93, 100, 98, 99, 100, 92, 97.00, 96.50, 99.80, 96.24, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (57, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (58, 1, 74, 72, 72, 70, 70, 75, 74, 78, 73, 77, 72.60, 72.25, 74.00, 74.27, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (59, 1, 92, 90, 85, 88, 90, 91, 90, 95, 92, 83, 88.10, 89.75, 92.60, 88.25, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (60, 1, 100, 95, 98, 98, 96, 99, 98, 100, 100, 97, 98.00, 97.75, 100.00, 98.25, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (60, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (61, 1, 80, 69, 78, 78, 70, 76, 68, 83, 77, 68, 76.80, 73.00, 78.20, 73.82, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (61, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (62, 1, 98, 94, 93, 100, 95, 97, 99, 99, 100, 100, 94.70, 97.75, 99.80, 98.43, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (62, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (63, 1, 72, 69, 66, 71, 68, 75, 69, 79, 69, 65, 68.40, 70.75, 71.00, 68.63, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (63, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (64, 1, 100, 94, 94, 97, 96, 100, 98, 99, 93, 97, 95.80, 97.75, 94.20, 96.07, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (64, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (65, 1, 88, 87, 86, 88, 83, 83, 89, 94, 83, 83, 86.80, 85.75, 85.20, 84.97, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (65, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (66, 1, 89, 80, 84, 79, 74, 76, 82, 82, 82, 76, 84.70, 77.75, 82.00, 79.89, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (67, 1, 100, 100, 99, 100, 100, 99, 100, 100, 98, 100, 99.50, 99.75, 98.40, 99.37, '优秀');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (68, 1, 100, 97, 97, 93, 100, 93, 96, 97, 92, 96, 97.90, 95.50, 93.00, 95.38, '优秀');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (69, 1, 90, 80, 85, 82, 88, 86, 84, 94, 84, 81, 85.50, 85.00, 86.00, 84.20, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (69, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (70, 1, 74, 66, 69, 73, 73, 75, 67, 80, 73, 69, 69.90, 72.00, 74.40, 71.40, '中等');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (70, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (71, 1, 87, 89, 88, 88, 80, 87, 82, 93, 86, 88, 87.90, 84.25, 87.40, 87.05, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (71, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (72, 1, 98, 87, 94, 95, 93, 90, 85, 97, 95, 93, 93.80, 90.75, 95.40, 93.43, '优秀');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (73, 1, 88, 83, 81, 83, 82, 84, 81, 92, 88, 83, 83.50, 82.50, 88.80, 84.74, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (73, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (74, 1, 88, 86, 81, 85, 80, 87, 78, 84, 86, 86, 84.10, 82.50, 85.60, 84.80, '良好');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (74, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (75, 1, 73, 73, 67, 76, 71, 76, 67, 75, 77, 71, 70.00, 72.50, 76.60, 72.78, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (76, 1, 95, 89, 83, 86, 86, 92, 89, 90, 86, 91, 87.80, 88.25, 86.80, 88.55, '良好');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (77, 1, 100, 92, 89, 90, 90, 94, 91, 93, 94, 93, 92.90, 91.25, 93.80, 92.87, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (77, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (78, 1, 69, 67, 68, 63, 66, 63, 65, 70, 66, 71, 68.10, 64.25, 66.80, 67.81, '及格');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (79, 1, 94, 86, 84, 94, 89, 94, 94, 92, 91, 91, 87.40, 92.75, 91.20, 90.69, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (79, 1, '满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (80, 1, 93, 89, 95, 92, 93, 91, 93, 91, 94, 88, 93.20, 92.25, 93.40, 91.51, '优秀');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (80, 1, '非常满意');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (81, 1, 78, 65, 73, 74, 71, 66, 73, 74, 75, 72, 72.90, 71.00, 74.80, 72.82, '中等');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (82, 1, 62, 58, 60, 58, 60, 63, 62, 72, 67, 66, 60.20, 60.75, 68.00, 64.39, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (82, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (83, 1, 71, 72, 65, 64, 71, 64, 66, 77, 72, 69, 68.20, 66.25, 73.00, 69.49, '及格');
INSERT INTO satisfaction_surveys (student_id, course_id, satisfaction_level) VALUES (83, 1, '一般');
INSERT INTO scores (student_id, course_id, attendance_score, performance_score, homework_score, test1_score, test2_score, test3_score, test4_score, lab_attendance_score, lab_report_score, final_exam_score, regular_aggregate, test_aggregate, lab_aggregate, total_score, grade_label) VALUES (84, 1, 86, 81, 75, 81, 81, 84, 77, 89, 77, 78, 79.50, 80.75, 79.40, 79.27, '中等');
